# Generated by Django 5.0.6 on 2024-05-20 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='maxJoueurs',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='nomVille',
        ),
        migrations.AddField(
            model_name='braqueur',
            name='agilite',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='braqueur',
            name='charisme',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='braqueur',
            name='communication',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='braqueur',
            name='discretion',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='braqueur',
            name='force',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='braqueur',
            name='hacking',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='braqueur',
            name='intelligence',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='braqueur',
            name='intimidation',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='braqueur',
            name='quote',
            field=models.TextField(default='', max_length=65535),
        ),
        migrations.AddField(
            model_name='equipe',
            name='maxEquipe',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='equipe',
            name='maxEspion',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='equipe',
            name='maxForger',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='equipe',
            name='maxHacker',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='equipe',
            name='maxHomme',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='equipe',
            name='maxLeader',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='equipe',
            name='maxMaitre',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='equipe',
            name='maxTechnicien',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='equipe',
            name='numberEquipe',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='pays',
            name='nomCapitale',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='braqueur',
            name='nomBraqueur',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='braqueur',
            name='prenomBraqueur',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='braqueur',
            name='telephone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='continent',
            name='nomContinent',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pays',
            name='imagePays',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pays',
            name='nomPays',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='nomRole',
            field=models.CharField(default='', max_length=50),
        ),
    ]
