# Generated by Django 5.0.6 on 2024-05-20 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heist', '0002_remove_equipe_maxjoueurs_remove_equipe_nomville_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='braqueurimage',
            name='braqueur',
        ),
        migrations.DeleteModel(
            name='Braqueur',
        ),
        migrations.DeleteModel(
            name='BraqueurImage',
        ),
    ]
