from django_seed import Seed
from .models import *
import random

EtatsUnis =  Pays.objects.get(pk=23)
Japon =  Pays.objects.get(pk=42)
France =  Pays.objects.get(pk=27)
RoyaumeUni =  Pays.objects.get(pk=83)
Cuba =  Pays.objects.get(pk=18)
Mexique =  Pays.objects.get(pk=59)
Irak =  Pays.objects.get(pk=50)

Ocean =  Equipe.objects.get(pk=1)
Phantom =  Equipe.objects.get(pk=2)
Hearth =  Equipe.objects.get(pk=3)
Gentlemen =  Equipe.objects.get(pk=4)
Lupin =  Equipe.objects.get(pk=5)
BlackPearl =  Equipe.objects.get(pk=6)
MerryMen =  Equipe.objects.get(pk=7)

Leader =  Role.objects.get(pk=1)
Hacker =  Role.objects.get(pk=2)
Espion =  Role.objects.get(pk=3)
Forger =  Role.objects.get(pk=4)
Maitre =  Role.objects.get(pk=5)
Technicien =  Role.objects.get(pk=6)
Homme =  Role.objects.get(pk=7)

entries = [
    {'nomBraqueur': "Ocean", 'prenomBraqueur': "Danny", 'age': 41, 'telephone': "1234567890", 'email': "danny.ocean@gmail.com", 'genre': "M", 'quote': "Because the house always wins. Play long enough, you never change the stakes, the house takes you. Unless, when that perfect hand comes along, you bet big, and then you take the house.",'charisme': 95, 'communication': 84, 'force': 67, 'discretion': 34, 'agilite': 41, 'intelligence': 82, 'intimidation': 71, 'hacking': 28, 'pays': EtatsUnis, 'equipe': Ocean, 'role': Leader},
    {'nomBraqueur': "Ryan", 'prenomBraqueur': "Rusty", 'age': 38, 'telephone': "1234567890", 'email': "rusty.ryan@gmail.com", 'genre': "M", 'quote': "You look down, they know you're lying and up, they know you don't know the truth. Don't use seven words when four will do. Don't shift your weight, look always at your mark but don't stare, be specific but not memorable, be funny but don't make him laugh. He's got to like you then forget you the moment you've left his side. And for God's sake, whatever you do, don't, under any circumstances...",'charisme': 98, 'communication': 97, 'force': 44, 'discretion': 64, 'agilite': 32, 'intelligence': 90, 'intimidation': 78, 'hacking': 33, 'pays': EtatsUnis, 'equipe': Ocean, 'role': Homme},
    {'nomBraqueur': "Caldwell", 'prenomBraqueur': "Linus", 'age': 31, 'telephone': "1234567890", 'email': "linus.caldwell@gmail.com", 'genre': "M", 'quote': "This is the best part of my day.", 'charisme': 58, 'communication': 67, 'force': 70, 'discretion': 92, 'agilite': 87, 'intelligence': 80, 'intimidation': 49, 'hacking': 51, 'pays': EtatsUnis, 'equipe': Ocean, 'role': Espion},
    {'nomBraqueur': "Bloom", 'prenomBraqueur': "Saul", 'age': 73, 'telephone': "1234567890", 'email': "saul.bloom@gmail.com", 'genre': "M", 'quote': "If you ever ask me that question again Daniel, you will not wake up the following morning.", 'charisme': 89, 'communication': 83, 'force': 11, 'discretion': 86, 'agilite': 5, 'intelligence': 61, 'intimidation': 66, 'hacking': 0, 'pays': EtatsUnis, 'equipe': Ocean, 'role': Maitre},
    {'nomBraqueur': "Malloy", 'prenomBraqueur': "Turk", 'age': 34, 'telephone': "1234567890", 'email': "turk.malloy@gmail.com", 'genre': "M", 'quote': "I'm gonna get out of the car and I'm gonna drop you like third-period French.", 'charisme': 73, 'communication': 76, 'force': 79, 'discretion': 65, 'agilite': 64, 'intelligence': 71, 'intimidation': 77, 'hacking': 50, 'pays': EtatsUnis, 'equipe': Ocean, 'role': Homme},
    {'nomBraqueur': "Malloy", 'prenomBraqueur': "Virgil", 'age': 34, 'telephone': "1234567890", 'email': "virgil.malloy@gmail.com", 'genre': "M", 'quote': "Man, I told you to run.", 'charisme': 73, 'communication': 76, 'force': 79, 'discretion': 65, 'agilite': 64, 'intelligence': 71, 'intimidation': 77, 'hacking': 50, 'pays': EtatsUnis, 'equipe': Ocean, 'role': Homme},
    {'nomBraqueur': "", 'prenomBraqueur': "Yen", 'age': 27, 'telephone': "1234567890", 'email': "yen.x@gmail.com", 'genre': "M", 'quote': "Where the f*** you been?", 'charisme': 63, 'communication': 15, 'force': 39, 'discretion': 80, 'agilite': 98, 'intelligence': 51, 'intimidation': 22, 'hacking': 23, 'pays': EtatsUnis, 'equipe': Ocean, 'role': Espion},
    {'nomBraqueur': "Tarr", 'prenomBraqueur': "Basher", 'age': 36, 'telephone': "1234567890", 'email': "basher.tarr@gmail.com", 'genre': "M", 'quote': "But see, a pinch creates a similar electromagnetic pulse, but without the fuss of mass destruction and death. So instead of Hiroshima, you'd be getting the seventeenth century.", 'charisme': 79, 'communication': 87, 'force': 59, 'discretion': 50, 'agilite': 62, 'intelligence': 93, 'intimidation': 72, 'hacking': 81, 'pays': EtatsUnis, 'equipe': Ocean, 'role': Technicien},
    {'nomBraqueur': "Catton", 'prenomBraqueur': "Frank", 'age': 39, 'telephone': "1234567890", 'email': "frank.catton@gmail.com", 'genre': "M", 'quote': "They might as well call it whitejack!", 'charisme': 87, 'communication': 91, 'force': 71, 'discretion': 42, 'agilite': 20, 'intelligence': 70, 'intimidation': 86, 'hacking': 33, 'pays': EtatsUnis, 'equipe': Ocean, 'role': Maitre},
    {'nomBraqueur': "Dell", 'prenomBraqueur': "Livingstone", 'age': 31, 'telephone': "1234567890", 'email': "livingstone.dell@gmail.com", 'genre': "M", 'quote': "Uh, do you see me grabbing the gun out of your holster and just waving it around?", 'charisme': 17, 'communication': 25, 'force': 34, 'discretion': 77, 'agilite': 44, 'intelligence': 89, 'intimidation': 8, 'hacking': 95, 'pays': EtatsUnis, 'equipe': Ocean, 'role': Hacker},
    {'nomBraqueur': "Lucilfer", 'prenomBraqueur': "Chrollo", 'age': 28, 'telephone': "1234567890", 'email': "chrollo.lucilfer@gmail.com", 'genre': "M", 'quote': "Together, we are the Spider. I'm its head, and you're the legs. The legs do what the head says. But there will be times when the legs are more important than the head. If I die, someone else will take over. My orders are of the utmost priority. My life is not. Be sure to make the right decision. I'm only a part of the Spider. What's important is the survival of the whole, not the individual.", 'charisme': 93, 'communication': 75, 'force': 88, 'discretion': 77, 'agilite': 69, 'intelligence': 80, 'intimidation': 90, 'hacking': 33, 'pays': Japon, 'equipe': Phantom, 'role': Leader},
    {'nomBraqueur': "Morow", 'prenomBraqueur': "Hisoka", 'age': 33, 'telephone': "1234567890", 'email': "hisoka.morow@gmail.com", 'genre': "M", 'quote': "There will be no rules or points next time.♠ It'll be life or death.♠", 'charisme': 83, 'communication': 84, 'force': 87, 'discretion': 90, 'agilite': 92, 'intelligence': 89, 'intimidation': 85, 'hacking': 58, 'pays': France, 'equipe': Phantom, 'role': Maitre},
    {'nomBraqueur': "Hazama", 'prenomBraqueur': "Nobunaga", 'age': 28, 'telephone': "1234567890", 'email': "nobunaga.hazama@gmail.com", 'genre': "M", 'quote': "Have you forgotten the unspoken rule? Use any means to bring him back, dead or alive. I don't care how you interpret that. Just stop telling me what to think.", 'charisme': 65, 'communication': 57, 'force': 77, 'discretion': 40, 'agilite': 72, 'intelligence': 68, 'intimidation': 75, 'hacking': 18, 'pays': Japon, 'equipe': Phantom, 'role': Homme},
    {'nomBraqueur': "Portor", 'prenomBraqueur': "Feitan", 'age': 23, 'telephone': "1234567890", 'email': "feitan.portor@gmail.com", 'genre': "M", 'quote': "We bandits. We here to steal.", 'charisme': 43, 'communication': 38, 'force': 87, 'discretion': 84, 'agilite': 88, 'intelligence': 80, 'intimidation': 82, 'hacking': 40, 'pays': Japon, 'equipe': Phantom, 'role': Espion},
    {'nomBraqueur': "Komacine", 'prenomBraqueur': "Machi", 'age': 25, 'telephone': "1234567890", 'email': "machi.komacine@gmail.com", 'genre': "F", 'quote': "I was never quite sure before, but that match proved it to me. You're an idiot.", 'charisme': 66, 'communication': 60, 'force': 55, 'discretion': 71, 'agilite': 78, 'intelligence': 80, 'intimidation': 60, 'hacking': 47, 'pays': Japon, 'equipe': Phantom, 'role': Technicien},
    {'nomBraqueur': "Magcub", 'prenomBraqueur': "Phinks", 'age': 27, 'telephone': "1234567890", 'email': "phinks.magcub@gmail.com", 'genre': "M", 'quote': "Deceive your allies to deceive your enemies, as they say.", 'charisme': 66, 'communication': 60, 'force': 75, 'discretion': 51, 'agilite': 68, 'intelligence': 70, 'intimidation': 77, 'hacking': 27, 'pays': Japon, 'equipe': Phantom, 'role': Homme},
    {'nomBraqueur': "Bordeau", 'prenomBraqueur': "Franklin", 'age': 37, 'telephone': "1234567890", 'email': "franklin.bordeau@gmail.com", 'genre': "M", 'quote': "The worst case is all of us dying. The end of the Spiders.", 'charisme': 76, 'communication': 80, 'force': 75, 'discretion': 31, 'agilite': 28, 'intelligence': 87, 'intimidation': 77, 'hacking': 27, 'pays': Japon, 'equipe': Phantom, 'role': Homme},
    {'nomBraqueur': "Murasaki", 'prenomBraqueur': "Shizuku", 'age': 22, 'telephone': "1234567890", 'email': "shizuku.murasaki@gmail.com", 'genre': "F", 'quote': "Breaking the rules means rejecting the Spiders, and Chrollo, too. That I never want to do.", 'charisme': 66, 'communication': 70, 'force': 65, 'discretion': 71, 'agilite': 78, 'intelligence': 57, 'intimidation': 37, 'hacking': 57, 'pays': Japon, 'equipe': Phantom, 'role': Technicien},
    {'nomBraqueur': "Ryuseih", 'prenomBraqueur': "Shalnark", 'age': 26, 'telephone': "1234567890", 'email': "shalnark.ryuseih@gmail.com", 'genre': "M", 'quote': "Aw, he broke. Gotta look for another puppet.", 'charisme': 82, 'communication': 88, 'force': 45, 'discretion': 64, 'agilite': 78, 'intelligence': 92, 'intimidation': 37, 'hacking': 74, 'pays': Japon, 'equipe': Phantom, 'role': Hacker},
    {'nomBraqueur': "", 'prenomBraqueur': "Pakunoda", 'age': 29, 'telephone': "1234567890", 'email': "pakunoda.x@gmail.com", 'genre': "F", 'quote': "I extract the memories that are beneath your consciousness. I don't read your surface thoughts. My questions stimulate your memories. They're brought to the surface the way a stone thrown into a pond stirs up sediment. They are the original, unprocessed memories... and I scoop them out. They're impossible to falsify.", 'charisme': 63, 'communication': 78, 'force': 45, 'discretion': 60, 'agilite': 68, 'intelligence': 83, 'intimidation': 57, 'hacking': 36, 'pays': Japon, 'equipe': Phantom, 'role': Technicien},
    {'nomBraqueur': "", 'prenomBraqueur': "Uvogin", 'age': 32, 'telephone': "1234567890", 'email': "uvogin.x@gmail.com", 'genre': "M", 'quote': "I never carry cash, unlike you. I steal whatever I want.", 'charisme': 55, 'communication': 60, 'force': 95, 'discretion': 10, 'agilite': 28, 'intelligence': 71, 'intimidation': 86, 'hacking': 0, 'pays': Japon, 'equipe': Phantom, 'role': Homme},
    {'nomBraqueur': "", 'prenomBraqueur': "Kortopi", 'age': 18, 'telephone': "1234567890", 'email': "kortopi.x@gmail.com", 'genre': "M", 'quote': "I can do another fifty. And the instant anyone enters a fake base, I'll know.", 'charisme': 35, 'communication': 20, 'force': 15, 'discretion': 70, 'agilite': 78, 'intelligence': 71, 'intimidation': 0, 'hacking': 50, 'pays': Japon, 'equipe': Phantom, 'role': Forger},
    {'nomBraqueur': "Lawliet", 'prenomBraqueur': "L", 'age': 18, 'telephone': "1234567890", 'email': "l.lawliet@gmail.com", 'genre': "M", 'quote': "He who moves first always wins.", 'charisme': 75, 'communication': 83, 'force': 50, 'discretion': 70, 'agilite': 88, 'intelligence': 97, 'intimidation': 68, 'hacking': 70, 'pays': Japon, 'equipe': None, 'role': Leader},
    {'nomBraqueur': "Yagami", 'prenomBraqueur': "Light", 'age': 18, 'telephone': "1234567890", 'email': "light.yagami@gmail.com", 'genre': "M", 'quote': "You can't ever win if you're always on the defensive, to win, you have to attack.", 'charisme': 75, 'communication': 89, 'force': 50, 'discretion': 70, 'agilite': 88, 'intelligence': 97, 'intimidation': 68, 'hacking': 70, 'pays': Japon, 'equipe': None, 'role': Leader},
    {'nomBraqueur': "Lupin", 'prenomBraqueur': "Arsène", 'age': 27, 'telephone': "1234567890", 'email': "arsène.lupin@gmail.com", 'genre': "M", 'quote': "What a pity that I am not an honest man!", 'charisme': 98, 'communication': 93, 'force': 50, 'discretion': 88, 'agilite': 88, 'intelligence': 84, 'intimidation': 53, 'hacking': 0, 'pays': France, 'equipe': Hearth, 'role': Maitre},
    {'nomBraqueur': "Holmes", 'prenomBraqueur': "Sherlock", 'age': 34, 'telephone': "1234567890", 'email': "sherlock.holmes@gmail.com", 'genre': "M", 'quote': "There is nothing more deceptive than an obvious fact.", 'charisme': 84, 'communication': 87, 'force': 70, 'discretion': 68, 'agilite': 70, 'intelligence': 98, 'intimidation': 43, 'hacking': 0, 'pays': RoyaumeUni, 'equipe': Hearth, 'role': Leader},
    {'nomBraqueur': "Moriarty", 'prenomBraqueur': "James", 'age': 41, 'telephone': "1234567890", 'email': "james.moriarty@gmail.com", 'genre': "M", 'quote': "Every fairy tale needs a good old-fashioned villain. You need me, or you're nothing. Because we're just alike, you and I. Except you're boring. You're on the side of the angels.", 'charisme': 84, 'communication': 87, 'force': 50, 'discretion': 88, 'agilite': 50, 'intelligence': 92, 'intimidation': 73, 'hacking': 0, 'pays': RoyaumeUni, 'equipe': None, 'role': Leader},
    {'nomBraqueur': "Bond", 'prenomBraqueur': "James", 'age': 25, 'telephone': "1234567890", 'email': "james.bond@gmail.com", 'genre': "M", 'quote': "Oh, I travel - A sort of licensed troubleshooter.", 'charisme': 97, 'communication': 82, 'force': 80, 'discretion': 88, 'agilite': 80, 'intelligence': 82, 'intimidation': 93, 'hacking': 20, 'pays': RoyaumeUni, 'equipe': None, 'role': Maitre},
    {'nomBraqueur': "Adler", 'prenomBraqueur': "Irene", 'age': 38, 'telephone': "1234567890", 'email': "irene.adler@gmail.com", 'genre': "F", 'quote': "Life is seldom about the destination, Sherlock,", 'charisme': 94, 'communication': 93, 'force': 40, 'discretion': 89, 'agilite': 80, 'intelligence': 87, 'intimidation': 53, 'hacking': 0, 'pays': RoyaumeUni, 'equipe': None, 'role': Maitre},
    {'nomBraqueur': "Kyle", 'prenomBraqueur': "Selina", 'age': 24, 'telephone': "1234567890", 'email': "selina.kyle@gmail.com", 'genre': "F", 'quote': "Honey I'm Home! Oh, Thats Right, I Forgot, I'm Not Married.", 'charisme': 94, 'communication': 82, 'force': 70, 'discretion': 97, 'agilite': 98, 'intelligence': 82, 'intimidation': 66, 'hacking': 40, 'pays': EtatsUnis, 'equipe': None, 'role': Espion},
    {'nomBraqueur': "Lupin III", 'prenomBraqueur': "Arsène", 'age': 33, 'telephone': "1234567890", 'email': "arsène.lupinIII@gmail.com", 'genre': "M", 'quote': "Criminals have always been in the know before anybody else. It's been like that for centuries.", 'charisme': 81, 'communication': 75, 'force': 80, 'discretion': 68, 'agilite': 78, 'intelligence': 92, 'intimidation': 76, 'hacking': 10, 'pays': Japon, 'equipe': Lupin, 'role': Leader},
    {'nomBraqueur': "Mine", 'prenomBraqueur': "Fujiko", 'age': 29, 'telephone': "1234567890", 'email': "fujiko.mine@gmail.com", 'genre': "F", 'quote': "I don't know. 'Never' is a very long time.", 'charisme': 96, 'communication': 87, 'force': 52, 'discretion': 86, 'agilite': 81, 'intelligence': 82, 'intimidation': 46, 'hacking': 20, 'pays': Japon, 'equipe': Lupin, 'role': Maitre},
    {'nomBraqueur': "Jigen", 'prenomBraqueur': "Daisuke", 'age': 33, 'telephone': "1234567890", 'email': "daisuke.jigen@gmail.com", 'genre': "M", 'quote': "Good question. The life of a thief might not be so bad.", 'charisme': 76, 'communication': 79, 'force': 82, 'discretion': 66, 'agilite': 61, 'intelligence': 72, 'intimidation': 86, 'hacking': 50, 'pays': Japon, 'equipe': Lupin, 'role': Homme},
    {'nomBraqueur': "Takamaki", 'prenomBraqueur': "Ann", 'age': 18, 'telephone': "1234567890", 'email': "ann.takamaki@gmail.com", 'genre': "F", 'quote': "I've made up my mind. I'm going to keep looking forward. Things like dying or losing aren't important now. All that matters is that I don't return to my old self. ...I'll never make a mistake like that again. I swear it!", 'charisme': 76, 'communication': 79, 'force': 72, 'discretion': 86, 'agilite': 91, 'intelligence': 72, 'intimidation': 56, 'hacking': 30, 'pays': Japon, 'equipe': Hearth, 'role': Technicien},
    {'nomBraqueur': "Amamiya", 'prenomBraqueur': "Ren", 'age': 18, 'telephone': "1234567890", 'email': "ren.amamiya@gmail.com", 'genre': "M", 'quote': "Yes, before this happens, we will take this country!", 'charisme': 88, 'communication': 73, 'force': 92, 'discretion': 91, 'agilite': 87, 'intelligence': 72, 'intimidation': 76, 'hacking': 50, 'pays': Japon, 'equipe': Hearth, 'role': Leader},
    {'nomBraqueur': "", 'prenomBraqueur': "Morgana", 'age': 18, 'telephone': "1234567890", 'email': "morgana.x@gmail.com", 'genre': "M", 'quote': "Don't call me a cat! I am Morgana!", 'charisme': 58, 'communication': 83, 'force': 32, 'discretion': 81, 'agilite': 77, 'intelligence': 72, 'intimidation': 26, 'hacking': 70, 'pays': Japon, 'equipe': Hearth, 'role': Espion},
    {'nomBraqueur': "Sakamoto", 'prenomBraqueur': "Ryuji", 'age': 18, 'telephone': "1234567890", 'email': "ryuji.sakamoto@gmail.com", 'genre': "M", 'quote': "You might not know where it's taking you, but the only choice you got is to keep running forward.", 'charisme': 78, 'communication': 63, 'force': 72, 'discretion': 51, 'agilite': 77, 'intelligence': 52, 'intimidation': 56, 'hacking': 30, 'pays': Japon, 'equipe': Hearth, 'role': Homme},
    {'nomBraqueur': "Kitagawa", 'prenomBraqueur': "Yusuke", 'age': 18, 'telephone': "1234567890", 'email': "yusuke.kitagawa@gmail.com", 'genre': "M", 'quote': "A breathtaking sight... Imitations they may be, but together, they make a fine spectacle... Though the flowers of evil may bloom, be it known... Abominations are fated to perish!", 'charisme': 88, 'communication': 83, 'force': 72, 'discretion': 81, 'agilite': 87, 'intelligence': 72, 'intimidation': 56, 'hacking': 30, 'pays': Japon, 'equipe': Hearth, 'role': Forger},
    {'nomBraqueur': "Niijima", 'prenomBraqueur': "Makoto", 'age': 18, 'telephone': "1234567890", 'email': "makoto.niijima@gmail.com", 'genre': "F", 'quote': "Before you guys came along, my life was defined by rules, set on a path of someone else's choosing... But only a true loser would live such a rigid life! I... I will win... Even if it means going up against the entire world!", 'charisme': 68, 'communication': 73, 'force': 72, 'discretion': 71, 'agilite': 77, 'intelligence': 72, 'intimidation': 56, 'hacking': 30, 'pays': Japon, 'equipe': Hearth, 'role': Homme},
    {'nomBraqueur': "Futaba", 'prenomBraqueur': "Sakura", 'age': 18, 'telephone': "1234567890", 'email': "sakura.futaba@gmail.com", 'genre': "F", 'quote': "Before you guys came along, my life was defined by rules, set on a path of someone else's choosing... But only a true loser would live such a rigid life! I... I will win... Even if it means going up against the entire world!", 'charisme': 48, 'communication': 53, 'force': 42, 'discretion': 91, 'agilite': 67, 'intelligence': 92, 'intimidation': 26, 'hacking': 90, 'pays': Japon, 'equipe': Hearth, 'role': Hacker},
    {'nomBraqueur': "Okumura", 'prenomBraqueur': "Haru", 'age': 18, 'telephone': "1234567890", 'email': "haru.okumura@gmail.com", 'genre': "F", 'quote': "Even if there are times where I think there's nothing I can do... I'll never stop fighting for you, or our team!", 'charisme': 91, 'communication': 84, 'force': 42, 'discretion': 81, 'agilite': 87, 'intelligence': 72, 'intimidation': 46, 'hacking': 20, 'pays': Japon, 'equipe': Hearth, 'role': Maitre},
    {'nomBraqueur': "Akechi", 'prenomBraqueur': "Goro", 'age': 18, 'telephone': "1234567890", 'email': "goro.akechi@gmail.com", 'genre': "M", 'quote': "I will carve my own path for myself… I refuse to accept a reality concocted by someone else, stuck under their control for the rest of my days.", 'charisme': 81, 'communication': 84, 'force': 62, 'discretion': 71, 'agilite': 77, 'intelligence': 72, 'intimidation': 56, 'hacking': 20, 'pays': Japon, 'equipe': Hearth, 'role': Technicien},
    {'nomBraqueur': "Yoshizawa", 'prenomBraqueur': "Sumire", 'age': 18, 'telephone': "1234567890", 'email': "sumire.yoshizawa@gmail.com", 'genre': "F", 'quote': "I am myself! I'll never forget that again!", 'charisme': 77, 'communication': 74, 'force': 52, 'discretion': 81, 'agilite': 87, 'intelligence': 72, 'intimidation': 56, 'hacking': 20, 'pays': Japon, 'equipe': Hearth, 'role': Homme},
    {'nomBraqueur': "", 'prenomBraqueur': "Sophia", 'age': 18, 'telephone': "1234567890", 'email': "sophia.x@gmail.com", 'genre': "F", 'quote': "The power to push what's forced on a person, and still change for the better… that is the human heart.", 'charisme': 67, 'communication': 64, 'force': 52, 'discretion': 71, 'agilite': 87, 'intelligence': 72, 'intimidation': 36, 'hacking': 20, 'pays': Japon, 'equipe': Hearth, 'role': Homme},
    {'nomBraqueur': "Hasegawa", 'prenomBraqueur': "Zenkichi", 'age': 28, 'telephone': "1234567890", 'email': "zenkichi.hasegawa@gmail.com", 'genre': "M", 'quote': "Hmm, how should I put it? I'm just a knight in shining armor.", 'charisme': 87, 'communication': 84, 'force': 72, 'discretion': 71, 'agilite': 57, 'intelligence': 72, 'intimidation': 66, 'hacking': 20, 'pays': Japon, 'equipe': Hearth, 'role': Technicien},
    {'nomBraqueur': "McCauley", 'prenomBraqueur': "Neil", 'age': 45, 'telephone': "1234567890", 'email': "neil.mccauley@gmail.com", 'genre': "M", 'quote': "A guy told me one time, 'Don't let yourself get attached to anything you are not willing to walk out on in 30 seconds flat if you feel the heat around the corner.'", 'charisme': 77, 'communication': 74, 'force': 72, 'discretion': 51, 'agilite': 57, 'intelligence': 82, 'intimidation': 86, 'hacking': 40, 'pays': EtatsUnis, 'equipe': None, 'role': Leader},
    {'nomBraqueur': "Rider", 'prenomBraqueur': "Flynn", 'age': 23, 'telephone': "1234567890", 'email': "flynn.rider@gmail.com", 'genre': "M", 'quote': "Well, a fake reputation is all a man has.", 'charisme': 77, 'communication': 74, 'force': 72, 'discretion': 51, 'agilite': 57, 'intelligence': 82, 'intimidation': 86, 'hacking': 40, 'pays': EtatsUnis, 'equipe': None, 'role': Leader},
    {'nomBraqueur': "Felonius", 'prenomBraqueur': "Gru", 'age': 35, 'telephone': "1234567890", 'email': "gru.felonius@gmail.com", 'genre': "M", 'quote': "That book Was accidentally destroyed maliciously.", 'charisme': 67, 'communication': 64, 'force': 62, 'discretion': 31, 'agilite': 37, 'intelligence': 72, 'intimidation': 76, 'hacking': 60, 'pays': EtatsUnis, 'equipe': None, 'role': Leader},
    {'nomBraqueur': "Kuroba", 'prenomBraqueur': "Kaito", 'age': 25, 'telephone': "1234567890", 'email': "kaito.kuroba@gmail.com", 'genre': "M", 'quote': "A thief is a creative artist who takes his prey in style... But a detective is nothing more than a critic, who follows our footsteps...", 'charisme': 93, 'communication': 86, 'force': 42, 'discretion': 81, 'agilite': 77, 'intelligence': 82, 'intimidation': 56, 'hacking': 30, 'pays': Japon, 'equipe': None, 'role': Maitre},
    {'nomBraqueur': "Sparrow", 'prenomBraqueur': "Jack", 'age': 39, 'telephone': "1234567890", 'email': "jack.sparrow@gmail.com", 'genre': "M", 'quote': "Me? I'm dishonest, and a dishonest man you can always trust to be dishonest. Honestly. It's the honest ones you want to watch out for, because you can never predict when they're going to do something incredibly... stupid.", 'charisme': 98, 'communication': 71, 'force': 62, 'discretion': 51, 'agilite': 77, 'intelligence': 82, 'intimidation': 56, 'hacking': 0, 'pays': Cuba, 'equipe': BlackPearl, 'role': Leader},
    {'nomBraqueur': "Kurama", 'prenomBraqueur': "Yoko", 'age': 19, 'telephone': "1234567890", 'email': "yoko.kurama@gmail.com", 'genre': "M", 'quote': "Yoko is back, they cry.", 'charisme': 95, 'communication': 81, 'force': 92, 'discretion': 71, 'agilite': 87, 'intelligence': 92, 'intimidation': 96, 'hacking': 0, 'pays': Japon, 'equipe': None, 'role': Technicien},
    {'nomBraqueur': "", 'prenomBraqueur': "Puss in Boots", 'age': 7, 'telephone': "1234567890", 'email': "puss.inboots@gmail.com", 'genre': "M", 'quote': "Please, no, por favor, por favor, please no, I implore you. I was doing it for my family! My mother she's sick and my father he lives off the garbage. The king offered me much money and I have a little brother...", 'charisme': 91, 'communication': 81, 'force': 62, 'discretion': 97, 'agilite': 98, 'intelligence': 72, 'intimidation': 86, 'hacking': 0, 'pays': Mexique, 'equipe': None, 'role': Espion},
    {'nomBraqueur': "", 'prenomBraqueur': "Nami", 'age': 18, 'telephone': "1234567890", 'email': "nami.x@gmail.com", 'genre': "F", 'quote': "Life is like a pencil that will surely run out, but will leave the beautiful writing of life.", 'charisme': 71, 'communication': 81, 'force': 42, 'discretion': 77, 'agilite': 78, 'intelligence': 82, 'intimidation': 46, 'hacking': 0, 'pays': Japon, 'equipe': None, 'role': Technicien},
    {'nomBraqueur': "Hood", 'prenomBraqueur': "Robin", 'age': 28, 'telephone': "1234567890", 'email': "robin.hood@gmail.com", 'genre': "M", 'quote': "Rob? That's A Naughty Word, We Never Rob! Just Sort Of... Borrow A Bit From Those Who Can Afford It.", 'charisme': 81, 'communication': 71, 'force': 62, 'discretion': 77, 'agilite': 88, 'intelligence': 82, 'intimidation': 66, 'hacking': 0, 'pays': RoyaumeUni, 'equipe': MerryMen, 'role': Leader},
    {'nomBraqueur': "Corleone", 'prenomBraqueur': "Vito", 'age': 28, 'telephone': "1234567890", 'email': "vito.corleone@gmail.com", 'genre': "M", 'quote': "I make him an offer he don' refuse. Don' worry.", 'charisme': 91, 'communication': 71, 'force': 62, 'discretion': 87, 'agilite': 68, 'intelligence': 82, 'intimidation': 96, 'hacking': 0, 'pays': EtatsUnis, 'equipe': None, 'role': Leader},
    {'nomBraqueur': "", 'prenomBraqueur': "Joker", 'age': 38, 'telephone': "1234567890", 'email': "joker.x@gmail.com", 'genre': "M", 'quote': "Do I really look like a guy with a plan? You know what I am? I'm a dog chasing cars. I wouldn't know what to do with one if I caught it! You know, I just... *do* things.", 'charisme': 91, 'communication': 81, 'force': 62, 'discretion': 57, 'agilite': 78, 'intelligence': 92, 'intimidation': 86, 'hacking': 40, 'pays': EtatsUnis, 'equipe': None, 'role': Leader},
    {'nomBraqueur': "", 'prenomBraqueur': "Aladdin", 'age': 38, 'telephone': "1234567890", 'email': "aladdin.x@gmail.com", 'genre': "M", 'quote': "Genie, you're free!", 'charisme': 81, 'communication': 86, 'force': 45, 'discretion': 86, 'agilite': 84, 'intelligence': 72, 'intimidation': 56, 'hacking': 0, 'pays': Irak, 'equipe': None, 'role': Espion},
    {'nomBraqueur': "Hardy", 'prenomBraqueur': "Felicia", 'age': 24, 'telephone': "1234567890", 'email': "felicia.hardy@gmail.com", 'genre': "F", 'quote': "I'm not a hero. I'm a thief. Born a thief. Raised a thief. Will die a thief.", 'charisme': 81, 'communication': 86, 'force': 45, 'discretion': 90, 'agilite': 84, 'intelligence': 72, 'intimidation': 56, 'hacking': 0, 'pays': EtatsUnis, 'equipe': None, 'role': Espion},
    {'nomBraqueur': "Philips", 'prenomBraqueur': "Trevor", 'age': 42, 'telephone': "1234567890", 'email': "trevor.philips@gmail.com", 'genre': "M", 'quote': "...But I Did Kidnap His Wife.", 'charisme': 81, 'communication': 56, 'force': 75, 'discretion': 20, 'agilite': 44, 'intelligence': 52, 'intimidation': 86, 'hacking': 0, 'pays': EtatsUnis, 'equipe': None, 'role': Homme},
    {'nomBraqueur': "Johnson", 'prenomBraqueur': "Carl", 'age': 19, 'telephone': "1234567890", 'email': "carl.johnson@gmail.com", 'genre': "M", 'quote': "Lady, I'm A God Fearin', Peace Lovin' Man Of The People!", 'charisme': 85, 'communication': 76, 'force': 75, 'discretion': 40, 'agilite': 64, 'intelligence': 72, 'intimidation': 66, 'hacking': 0, 'pays': EtatsUnis, 'equipe': None, 'role': Homme},
]


def run():
    seeder = Seed.seeder()
    for i in entries:
        seeder.add_entity(Braqueur, 1, {
            'nomBraqueur': i['nomBraqueur'],
            'prenomBraqueur': i['prenomBraqueur'],
            'age': i['age'],
            'telephone': i['telephone'],
            'email': i['email'],
            'genre': i['genre'],
            'quote': i['quote'],
            'charisme': i['charisme'],
            'communication': i['communication'],
            'force': i['force'],
            'discretion': i['discretion'],
            'agilite': i['agilite'],
            'intelligence': i['intelligence'],
            'intimidation': i['intimidation'],
            'hacking': i['hacking'],
            'pays': i['pays'],
            'equipe': i['equipe'],
            'role': i['role'],
        })
    pks = seeder.execute()
    print(pks)