from django_seed import Seed
from .models import *
import random

Asie = Continent.objects.get(pk=1)
Afrique = Continent.objects.get(pk=2)
AmériqueduNord = Continent.objects.get(pk=3)
AmériqueduSud = Continent.objects.get(pk=4)
Europe = Continent.objects.get(pk=5)
Oceanie = Continent.objects.get(pk=6)
Antartique = Continent.objects.get(pk=7)

entries = [
    {'nomPays': "Afghanistan", 'nomCapitale': "Kaboul", 'imagePays': "/assets/img/afghanistan-flag.jpg", 'continent': Asie},
    {'nomPays': "Afrique du Sud", 'nomCapitale': "Le Cap", 'imagePays': "/assets/img/afrique-du-sud-flag.jpg", 'continent': Afrique},
    {'nomPays': "Algérie", 'nomCapitale': "	Alger", 'imagePays': "/assets/img/algérie-flag.jpg", 'continent': Afrique},
    {'nomPays': "Argentine", 'nomCapitale': "Buenos Aires", 'imagePays': "/assets/img/argentine-flag.jpg", 'continent': AmériqueduSud},
    {'nomPays': "Belgique", 'nomCapitale': "Bruxelles", 'imagePays': "/assets/img/belgique-flag.jpg", 'continent': Europe},
    {'nomPays': "Bolivie", 'nomCapitale': "La Paz", 'imagePays': "/assets/img/bolivie-flag.jpg", 'continent': AmériqueduSud},
    {'nomPays': "Brésil", 'nomCapitale': "Brasilia", 'imagePays': "/assets/img/brésil-flag.jpg", 'continent': AmériqueduSud},
    {'nomPays': "Cambodge", 'nomCapitale': "Phnom Penh", 'imagePays': "/assets/img/cambodge-flag.jpg", 'continent': Asie},
    {'nomPays': "Cameroun", 'nomCapitale': "Yaoundé", 'imagePays': "/assets/img/cameroun-flag.jpg", 'continent': Afrique},
    {'nomPays': "Canada", 'nomCapitale': "Ottawa", 'imagePays': "/assets/img/canada-flag.jpg", 'continent': AmériqueduNord},
    {'nomPays': "Cap-Vert", 'nomCapitale': "Praia", 'imagePays': "/assets/img/cap-vert-flag.jpg", 'continent': Afrique},
    {'nomPays': "Chine", 'nomCapitale': "Pékin",'imagePays': "/assets/img/chine-flag.jpg", 'continent': Asie},
    {'nomPays': "RD Congo", 'nomCapitale': "Kinshasa", 'imagePays': "/assets/img/congo-flag.jpg", 'continent': Afrique},
    {'nomPays': "Corée du Nord", 'nomCapitale': "Pyongyang", 'imagePays': "/assets/img/corrée-du-nord-flag.jpg", 'continent': Asie},
    {'nomPays': "Corée du Sud", 'nomCapitale': "Séoul", 'imagePays': "/assets/img/corrée-du-sud-flag.jpg", 'continent': Asie},
    {'nomPays': "Cote d'Ivoire", 'nomCapitale': "Abidjan", 'imagePays': "/assets/img/cote-d-ivoire-flag.jpg", 'continent': Afrique},
    {'nomPays': "Croatie", 'nomCapitale': "Zagreb", 'imagePays': "/assets/img/croatie-flag.jpg", 'continent': Europe},
    {'nomPays': "Cuba", 'nomCapitale': "La Havane", 'imagePays': "/assets/img/cuba-flag.jpg", 'continent': AmériqueduNord},
    {'nomPays': "Egypte", 'nomCapitale': "Le Caire", 'imagePays': "/assets/img/egypte-flag.jpg", 'continent': Afrique},
    {'nomPays': "Equateur", 'nomCapitale': "Quito", 'imagePays': "/assets/img/equateur-flag.jpg", 'continent': AmériqueduSud},
    {'nomPays': "Erythrée", 'nomCapitale': "Asmara", 'imagePays': "/assets/img/erythrée-flag.jpg", 'continent': Afrique},
    {'nomPays': "Espagne", 'nomCapitale': "Madrid", 'imagePays': "/assets/img/espagne-flag.jpg", 'continent': Europe},
    {'nomPays': "Etats-Unis", 'nomCapitale': "Washington, D.C.", 'imagePays': "/assets/img/etats-unis-flag.jpg", 'continent': AmériqueduNord},
    {'nomPays': "Ethiopie", 'nomCapitale': "Addis-Abeba", 'imagePays': "/assets/img/ethiopie-flag.jpg", 'continent': Afrique},
    {'nomPays': "Les iles Fidji", 'nomCapitale': "Suva", 'imagePays': "/assets/img/fidji-flag.jpg", 'continent': Oceanie},
    {'nomPays': "Finlande", 'nomCapitale': "Helsinki", 'imagePays': "/assets/img/finland-flag.jpg", 'continent': Europe},
    {'nomPays': "France", 'nomCapitale': "Paris", 'imagePays': "/assets/img/france-flag.jpg", 'continent': Europe},
    {'nomPays': "Gabon", 'nomCapitale': "Libreville", 'imagePays': "/assets/img/gabon-flag.jpg", 'continent': Afrique},
    {'nomPays': "Gambie", 'nomCapitale': "Banjul", 'imagePays': "/assets/img/gambie-flag.jpg", 'continent': Afrique},
    {'nomPays': "Géorgie", 'nomCapitale': "Tbilissi", 'imagePays': "/assets/img/georgie-flag.jpg", 'continent': Europe},
    {'nomPays': "Ghana", 'nomCapitale': "Accra", 'imagePays': "/assets/img/ghana-flag.jpg", 'continent': Afrique},
    {'nomPays': "Grèce", 'nomCapitale': "Athènes", 'imagePays': "/assets/img/greece-flag.jpg", 'continent': Europe},
    {'nomPays': "Guinée", 'nomCapitale': "Conakry", 'imagePays': "/assets/img/guinee-flag.jpg", 'continent': Afrique},
    {'nomPays': "Guyanne", 'nomCapitale': "Georgetown", 'imagePays': "/assets/img/guyanne-flag.jpg", 'continent': AmériqueduSud},
    {'nomPays': "Inde", 'nomCapitale': "New Delhi", 'imagePays': "/assets/img/inde-flag.jpg", 'continent': Asie},
    {'nomPays': "Indonésie", 'nomCapitale': "Jakarta", 'imagePays': "/assets/img/indonesie-flag.jpg", 'continent': Asie},
    {'nomPays': "Irak", 'nomCapitale': "Bagdad", 'imagePays': "/assets/img/irak-flag.jpg", 'continent': Asie},
    {'nomPays': "Iran", 'nomCapitale': "Téhéran", 'imagePays': "/assets/img/iran-flag.jpg", 'continent': Asie},
    {'nomPays': "Irlande", 'nomCapitale': "Dublin", 'imagePays': "/assets/img/ireland-flag.jpg", 'continent': Europe},
    {'nomPays': "Islande", 'nomCapitale': "Reykjavik", 'imagePays': "/assets/img/islande-flag.jpg", 'continent': Europe},
    {'nomPays': "Italie", 'nomCapitale': "Rome", 'imagePays': "/assets/img/italie-flag.jpg", 'continent': Europe},
    {'nomPays': "Japon", 'nomCapitale': "Tokyo", 'imagePays': "/assets/img/japon-flag.jpg", 'continent': Asie},
    {'nomPays': "Jordanie", 'nomCapitale': "Amman", 'imagePays': "/assets/img/jordanie-flag.jpg", 'continent': Asie},
    {'nomPays': "Kenya", 'nomCapitale': "Nairobi", 'imagePays': "/assets/img/kenya-flag.jpg", 'continent': Afrique},
    {'nomPays': "Kiribati", 'nomCapitale': "Tarawa-Sud", 'imagePays': "/assets/img/kiribati-flag.jpg", 'continent': Oceanie},
    {'nomPays': "Laos", 'nomCapitale': "Vientiane", 'imagePays': "/assets/img/laos-flag.jpg", 'continent': Asie},
    {'nomPays': "Liban", 'nomCapitale': "Beyrouth", 'imagePays': "/assets/img/liban-flag.jpg", 'continent': Asie},
    {'nomPays': "Libéria", 'nomCapitale': "Monrovia", 'imagePays': "/assets/img/liberia-flag.jpg", 'continent': Afrique},
    {'nomPays': "Libye", 'nomCapitale': "Tripoli", 'imagePays': "/assets/img/libye-flag.jpg", 'continent': Afrique},
    {'nomPays': "Lituanie", 'nomCapitale': "Vilnius", 'imagePays': "/assets/img/lituanie-flag.jpg", 'continent': Europe},
    {'nomPays': "Macédoine du Nord", 'nomCapitale': "Skopje", 'imagePays': "/assets/img/macedoine-du-nord-flag.jpg", 'continent': Europe},
    {'nomPays': "Madagascar", 'nomCapitale': "Antananarivo", 'imagePays': "/assets/img/madagascar-flag.jpg", 'continent': Afrique},
    {'nomPays': "Malaisie", 'nomCapitale': "Kuala Lumpur", 'imagePays': "/assets/img/malaisie-flag.jpg", 'continent': Asie},
    {'nomPays': "Malawi", 'nomCapitale': "Lilongwe", 'imagePays': "/assets/img/malawi-flag.jpg", 'continent': Afrique},
    {'nomPays': "Mali", 'nomCapitale': "Bamako", 'imagePays': "/assets/img/mali-flag.jpg", 'continent': Afrique},
    {'nomPays': "Malte", 'nomCapitale': "La Valette",'imagePays': "/assets/img/malte-flag.jpg", 'continent': Europe},
    {'nomPays': "Maroc", 'nomCapitale': "Rabat", 'imagePays': "/assets/img/maroc-flag.jpg", 'continent': Afrique},
    {'nomPays': "Mauritanie", 'nomCapitale': "Nouakchott", 'imagePays': "/assets/img/mauritanie-flag.jpg", 'continent': Afrique},
    {'nomPays': "Mexique", 'nomCapitale': "Mexico", 'imagePays': "/assets/img/mexique-flag.jpg", 'continent': AmériqueduNord},
    {'nomPays': "Moldavie", 'nomCapitale': "Chisinau", 'imagePays': "/assets/img/moldavie-flag.jpg", 'continent': Europe},
    {'nomPays': "Monaco", 'nomCapitale': "Commune de Monaco", 'imagePays': "/assets/img/monaco-flag.jpg", 'continent': Europe},
    {'nomPays': "Mongolie", 'nomCapitale': "Oulan-Bator", 'imagePays': "/assets/img/mongolie-flag.jpg", 'continent': Asie},
    {'nomPays': "Monténégro", 'nomCapitale': "Podgorica", 'imagePays': "/assets/img/montenegro-flag.jpg", 'continent': Europe},
    {'nomPays': "Mozambique", 'nomCapitale': "Maputo", 'imagePays': "/assets/img/mozambique-flag.jpg", 'continent': Afrique},
    {'nomPays': "Namibie", 'nomCapitale': "Windhoek", 'imagePays': "/assets/img/namibie-flag.jpg", 'continent': Afrique},
    {'nomPays': "Népal", 'nomCapitale': "Katmandou", 'imagePays': "/assets/img/nepal-flag.jpg", 'continent': Asie},
    {'nomPays': "Niger", 'nomCapitale': "Niamey", 'imagePays': "/assets/img/niger-flag.jpg", 'continent': Afrique},
    {'nomPays': "Nigéria", 'nomCapitale': "Abuja", 'imagePays': "/assets/img/nigeria-flag.jpg", 'continent': Afrique},
    {'nomPays': "Norvège", 'nomCapitale': "Oslo", 'imagePays': "/assets/img/norvege-flag.jpg", 'continent': Europe},
    {'nomPays': "Nouvelle-Zélande", 'nomCapitale': "Wellington", 'imagePays': "/assets/img/nouvelle-zélande-flag.jpg", 'continent': Oceanie},
    {'nomPays': "Oman", 'nomCapitale': "Mascate", 'imagePays': "/assets/img/oman-flag.jpg", 'continent': Asie},
    {'nomPays': "Ouganda", 'nomCapitale': "Kampala", 'imagePays': "/assets/img/ouganda-flag.jpg", 'continent': Afrique},
    {'nomPays': "Palaos", 'nomCapitale': "Melekeok", 'imagePays': "/assets/img/palos-flag.jpg", 'continent': Asie},
    {'nomPays': "Palestine", 'nomCapitale': "Ramallah", 'imagePays': "/assets/img/palestine-flag.jpg", 'continent': Asie},
    {'nomPays': "Papouasie-Nouvelle-Guinée", 'nomCapitale': "Port Moresby", 'imagePays': "/assets/img/papouasie-nouvelle-guinee-flag.jpg", 'continent': Asie},
    {'nomPays': "Paraguay", 'nomCapitale': "Asuncion", 'imagePays': "/assets/img/paraguay-flag.jpg", 'continent': AmériqueduSud},
    {'nomPays': "Pays-Bas", 'nomCapitale': "Amsterdam", 'imagePays': "/assets/img/pays-bas-flag.jpg", 'continent': Europe},
    {'nomPays': "Pérou", 'nomCapitale': "Lima", 'imagePays': "/assets/img/perou-flag.jpg", 'continent': AmériqueduSud},
    {'nomPays': "Philippines", 'nomCapitale': "Manille",'imagePays': "/assets/img/philippines-flag.jpg", 'continent': Asie},
    {'nomPays': "Pologne", 'nomCapitale': "	Varsovie", 'imagePays': "/assets/img/pologne-flag.jpg", 'continent': Europe},
    {'nomPays': "Portugal", 'nomCapitale': "Lisbonne", 'imagePays': "/assets/img/portugal-flag.jpg", 'continent': Europe},
    {'nomPays': "Roumanie", 'nomCapitale': "Bucarest", 'imagePays': "/assets/img/roumanie-flag.jpg", 'continent': Europe},
    {'nomPays': "Royaume-Uni", 'nomCapitale': "Londres", 'imagePays': "/assets/img/royaume-uni-flag.jpg", 'continent': Europe},
    {'nomPays': "Russie", 'nomCapitale': "Moscou", 'imagePays': "/assets/img/russie-flag.jpg", 'continent': Europe},
    {'nomPays': "Rwanda", 'nomCapitale': "Kigali", 'imagePays': "/assets/img/rwanda-flag.jpg", 'continent': Afrique},
    {'nomPays': "Samoa", 'nomCapitale': "Apia", 'imagePays': "/assets/img/samoa-flag.jpg", 'continent': Oceanie},
    {'nomPays': "Sao Tomé-et-Principe", 'nomCapitale': "São Tomé", 'imagePays': "/assets/img/sao-tome-et-principe-flag.jpg", 'continent': Afrique},
    {'nomPays': "Sénégal", 'nomCapitale': "Dakar", 'imagePays': "/assets/img/senegal-flag.jpg", 'continent': Afrique},
    {'nomPays': "Serbie", 'nomCapitale': "Belgrade",'imagePays': "/assets/img/serbie-flag.jpg", 'continent': Europe},
    {'nomPays': "Seychelles", 'nomCapitale': "Victoria", 'imagePays': "/assets/img/seychelles-flag.jpg", 'continent': Afrique},
    {'nomPays': "Sierra Leone", 'nomCapitale': "Freetown", 'imagePays': "/assets/img/sierra-leone-flag.jpg", 'continent': Afrique},
    {'nomPays': "Singapour", 'nomCapitale': "Singapour", 'imagePays': "/assets/img/singapore-flag.jpg", 'continent': Asie},
    {'nomPays': "Slovaquie", 'nomCapitale': "Bratislava", 'imagePays': "/assets/img/slovaquie-flag.jpg", 'continent': Europe},
    {'nomPays': "Slovénie", 'nomCapitale': "Ljubljana", 'imagePays': "/assets/img/slovenie-flag.jpg", 'continent': Europe},
    {'nomPays': "Somalie", 'nomCapitale': "Mogadiscio", 'imagePays': "/assets/img/somalie-flag.jpg", 'continent': Afrique},
    {'nomPays': "Soudan", 'nomCapitale': "Khartoum", 'imagePays': "/assets/img/soudan-flag.jpg", 'continent': Afrique},
    {'nomPays': "Sri Lanka", 'nomCapitale': "Kotte", 'imagePays': "/assets/img/sri-lanka-flag.jpg", 'continent': Asie},
    {'nomPays': "Suède", 'nomCapitale': "Stockholm", 'imagePays': "/assets/img/suede-flag.jpg", 'continent': Europe},
    {'nomPays': "Suisse", 'nomCapitale': "Berne", 'imagePays': "/assets/img/suisse-flag.jpg", 'continent': Europe},
    {'nomPays': "Suriname", 'nomCapitale': "Paramaribo",'imagePays': "/assets/img/suriname-flag.jpg", 'continent': AmériqueduSud},
    {'nomPays': "Syrie", 'nomCapitale': "Damas", 'imagePays': "/assets/img/syrie-flag.jpg", 'continent': Asie},
    {'nomPays': "Tanzanie", 'nomCapitale': "Dodoma", 'imagePays': "/assets/img/tanzanie-flag.jpg", 'continent': Afrique},
    {'nomPays': "Thailande", 'nomCapitale': "Bangkok", 'imagePays': "/assets/img/thailande-flag.jpg", 'continent': Asie},
    {'nomPays': "Togo", 'nomCapitale': "Lomé", 'imagePays': "/assets/img/togo-flag.jpg", 'continent': Afrique},
    {'nomPays': "Tunisie", 'nomCapitale': "Tunis", 'imagePays': "/assets/img/tunisie-flag.jpg", 'continent': Afrique},
    {'nomPays': "Turquie", 'nomCapitale': "Ankara", 'imagePays': "/assets/img/turquie-flag.jpg", 'continent': Europe},
    {'nomPays': "Ukraine", 'nomCapitale': "Kiev", 'imagePays': "/assets/img/ukraine-flag.jpg", 'continent': Europe},
    {'nomPays': "Uruguay", 'nomCapitale': "Montevideo", 'imagePays': "/assets/img/uruguay-flag.jpg", 'continent': AmériqueduSud},
    {'nomPays': "Vanuatu", 'nomCapitale': "Port-Vila", 'imagePays': "/assets/img/vanuatu-flag.jpg", 'continent': Oceanie},
    {'nomPays': "Venezuela", 'nomCapitale': "Caracas", 'imagePays': "/assets/img/venezuela-flag.jpg", 'continent': AmériqueduSud},
    {'nomPays': "Vietnam", 'nomCapitale': "Hanoï", 'imagePays': "/assets/img/vietnam-flag.jpg", 'continent': Asie},
    {'nomPays': "Yémen", 'nomCapitale': "Sanaa", 'imagePays': "/assets/img/yemen-flag.jpg", 'continent': Asie},
    {'nomPays': "Zambie", 'nomCapitale': "Lusaka",'imagePays': "/assets/img/zambie-flag.jpg", 'continent': Afrique},
    {'nomPays': "Zimbabwe", 'nomCapitale': "Harare", 'imagePays': "/assets/img/zimbabwe-flag.jpg", 'continent': Afrique},
]


def run():
    seeder = Seed.seeder()
    for i in entries:
        seeder.add_entity(Pays, 1, {
            'nomPays': i['nomPays'],
            'nomCapitale': i['nomCapitale'],
            'imagePays': i['imagePays'],
            'continent': i['continent'],
        })
    pks = seeder.execute()
    print(pks)